config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#main"

  get "/home", to: "pages#home"
  resources :bookmarks

  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "/logout", to: "sessions#destroy", via: [:get, :delete]

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  def self.find_or_create_from_auth_hash auth_hash, user: nil
    auth = find_by provider: auth_hash['provider'], uid: auth_hash['uid']
    return auth if auth

    user ||= User.create_from_auth_hash! auth_hash

    info = auth_hash['info']
    creds = auth_hash['credentials']

    Authorization.create(
      user: user,
      provider: auth_hash['provider'],
      uid: auth_hash['uid'],
      name: info['name'],
      nickname: info['nickname'],
      email: info['email'],
      image: info['image'],
      token: creds['token'],
      secret: creds['secret'],
      expires: creds['expires'],
      expires_at: creds['expires_at']
    )
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :webpage

  validates_presence_of :user_id, :webpage_id
  validates_uniqueness_of :webpage_id, scope: :user_id

  update_index('webpages#bookmark') { self }
end

app/models/scrape.rb
class Scrape < ApplicationRecord
  belongs_to :webpage

  update_index('webpages#webpage') { webpage }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authorizations
  has_many :bookmarks

  def self.create_from_auth_hash! auth_hash
    username = auth_hash.dig 'info', 'name'

    username ||= "test"

    create username: username
  end

  def owner_of? record
    record.user_id == self.id
  end
end

app/models/webpage.rb
class Webpage < ApplicationRecord
  has_many :bookmarks
  has_many :scrapes

  update_index('webpages#webpage') { self }
  after_commit :enqueue_scrape, on: :create

  def parsed_uri
    @parsed_uri ||= Addressable::URI.parse(uri)
  end

  def parsed_uri= val
    self.raw_uri = val
  end

  def latest_scrape
    @latest_scrape ||= scrapes.order(created_at: :desc).first
  end

  def enqueue_scrape
    ScrapeWebpageJob.perform_later(webpage: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :require_login

  protected

  def require_login
    redirect_to root_url unless signed_in?
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def signed_in?
    current_user.present?
  end

  helper_method :current_user, :signed_in?

  def current_user= user
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = policy_scope(Bookmark)
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @related_in_mine = WebpagesIndex.type_hash["webpage"]
      .query(
        bool: {
          must: [
            # {
            #   has_child: {
            #     type: :bookmark,
            #     query: {
            #       term: {
            #         user_id: current_user.id
            #       }
            #     }
            #   }
            # },
            {
              more_like_this: {
                fields: ["body"],
                like: [
                  { _id: @bookmark.webpage.id, _type: :webpage, _index: WebpagesIndex.index_name }
                ],
                min_term_freq: 20,
                max_query_terms: 30
              }
            }
          ]
        }
      ).objects
  end

  # GET /bookmarks/new
  def new
    @bookmark = current_user.bookmarks.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    webpage = Webpage.find_or_create_by(raw_uri: params.dig(:bookmark, :webpage, :raw_uri))
    @bookmark = current_user.bookmarks.new bookmark_params.merge(webpage: webpage)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update bookmark_params
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    @bookmark = authorize Bookmark.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bookmark_params
    permitted_attributes(@bookmark || Bookmark)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login, only: [ :main ]
  before_action :login_redirect, only: [ :main ]

  def main
  end

  def home
  end

  protected

  def login_redirect
    redirect_to "/home" if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :require_login, only: :create

  # https://seesparkbox.com/foundry/simulating_social_login_with_omniauth
  def create
    @auth = Authorization.find_or_create_from_auth_hash(auth_hash, user: current_user)

    # TODO: Handle not found
    self.current_user = @auth.user

    redirect_to request.env['omniauth.origin'] || home_url
  end

  def destroy
    self.current_user = nil
    redirect_to root_url
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_path provider
    "/auth/#{ provider.to_s }"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/_form.html.haml
= form_for @bookmark do |f|
  - if @bookmark.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bookmark.errors.count, "error")} prohibited this bookmark from being saved:"
      %ul
        - @bookmark.errors.full_messages.each do |message|
          %li= message

  = f.text_field :tags

  = f.fields_for :webpage, @bookmark.webpage do |webpage_f|
    = webpage_f.text_field :raw_uri

  .actions
    = f.submit 'Save'

app/views/bookmarks/edit.html.haml
%h1 Editing bookmark

= render 'form'

= link_to 'Show', @bookmark
\|
= link_to 'Back', bookmarks_path

app/views/bookmarks/index.html.haml
%h1 Listing bookmarks

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @bookmarks.each do |bookmark|
      %tr
        %td= bookmark.webpage.latest_scrape.title
        %td= link_to 'Show', bookmark
        %td= link_to 'Edit', edit_bookmark_path(bookmark)
        %td= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Bookmark', new_bookmark_path

app/views/bookmarks/new.html.haml
%h1 New bookmark

= render 'form'

= link_to 'Back', bookmarks_path

app/views/bookmarks/show.html.haml
%p#notice= notice

%h2= @bookmark.webpage.latest_scrape.title
%p= raw @bookmark.webpage.latest_scrape.content

%br

= link_to 'Edit', edit_bookmark_path(@bookmark)
\|
= link_to 'Back', bookmarks_path

%hr

%h3 Related
%h4 To your bookmarks

- @related_in_mine.each do |webpage|
  %h5= webpage.latest_scrape.title

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}

    %title Flagr

    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    = yield

  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/pages/home.html.haml
= link_to "New Bookmark", new_bookmark_path

app/views/pages/main.html.haml
= link_to "Login", login_path(:developer)